export class SizeConstants {
  /**
   * Default watch size in pixels setting.
   */
  static readonly FULL_SIZE_PX: string = '466px';
  /**
   * Default watch size in pixels setting.
   */
  static readonly WATCH_LIST_WIDTH_PX: string = '414px';
  /**
   * The width percentage setting.
   */
  static readonly FULL_WIDTH_PERCENT: string = '100%';
  /**
   * The height percentage setting.
   */
  static readonly FULL_HEIGHT_PERCENT: string = '100%';
  /**
   * The width percentage setting.
   */
  static readonly WIDTH_PERCENT_40: string = '40%';
  /**
   * The height percentage setting.
   */
  static readonly HEIGHT_PERCENT_40: string = '40%';
}